apiVersion: v1
kind: ConfigMap
metadata:
  name: olake-k8s-worker-config
  namespace: olake
  labels:
    app.kubernetes.io/name: olake-k8s-worker
    app.kubernetes.io/instance: olake
    app.kubernetes.io/component: worker
data:
  # Temporal Configuration
  TEMPORAL_ADDRESS: "temporal.olake.svc.cluster.local:7233"
  TEMPORAL_TASK_QUEUE: "OLAKE_K8S_TASK_QUEUE"
  
  # Database Configuration
  DB_HOST: "postgresql.olake.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "olake"
  DB_USER: "olake"
  DB_SSLMODE: "disable"
  
  # Kubernetes Configuration
  K8S_NAMESPACE: "olake"
  K8S_IMAGE_REGISTRY: "olakego"
  K8S_IMAGE_PULL_POLICY: "IfNotPresent"
  K8S_SERVICE_ACCOUNT: "olake-k8s-worker"
  
  # Job Configuration
  JOB_TTL_SECONDS: "0"  # 0 = no timeout for long-running sync jobs
  JOB_BACKOFF_LIMIT: "3"
  JOB_PARALLELISM: "1"
  JOB_COMPLETIONS: "1"
  
  # Resource Configuration
  JOB_CPU_REQUEST: "250m"
  JOB_CPU_LIMIT: "1000m"
  JOB_MEMORY_REQUEST: "512Mi"
  JOB_MEMORY_LIMIT: "2Gi"
  
  # Worker Configuration
  WORKER_MAX_CONCURRENT_ACTIVITIES: "10"
  WORKER_MAX_CONCURRENT_WORKFLOWS: "5"
  
  # Health Check Configuration
  HEALTH_CHECK_PORT: "8080"
  
  # Logging Configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
