apiVersion: v1
kind: ConfigMap
metadata:
  name: olake-k8s-worker-config
  namespace: olake
  labels:
    app.kubernetes.io/name: olake-k8s-worker
    app.kubernetes.io/instance: olake
    app.kubernetes.io/component: worker
data:
  # Temporal Configuration
  TEMPORAL_ADDRESS: "temporal.olake.svc.cluster.local:7233"
  TEMPORAL_TASK_QUEUE: "OLAKE_K8S_TASK_QUEUE"
  
  # Database Configuration
  DB_HOST: "postgresql.olake.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_USER: "temporal"
  DB_SSLMODE: "disable"
  
  # Timeout Configuration
  # Workflow execution timeouts (client-side)
  WORKFLOW_TIMEOUT_DISCOVER: "2h"
  WORKFLOW_TIMEOUT_TEST: "2h"
  WORKFLOW_TIMEOUT_SYNC: "6h"
  
  # Activity timeouts (workflow-side)
  ACTIVITY_TIMEOUT_DISCOVER: "30m"
  ACTIVITY_TIMEOUT_TEST: "30m"
  ACTIVITY_TIMEOUT_SYNC: "4h"
  
  # Kubernetes Configuration
  K8S_NAMESPACE: "olake"
  K8S_IMAGE_REGISTRY: "olakego"
  K8S_IMAGE_PULL_POLICY: "IfNotPresent"
  K8S_SERVICE_ACCOUNT: "olake-k8s-worker"
  
  # Job Configuration
  JOB_TTL_SECONDS: "0"  # 0 = no timeout for long-running sync jobs
  JOB_BACKOFF_LIMIT: "3"
  JOB_PARALLELISM: "1"
  JOB_COMPLETIONS: "1"
  
  # Resource Configuration
  JOB_CPU_REQUEST: "250m"
  JOB_CPU_LIMIT: "1000m"
  JOB_MEMORY_REQUEST: "512Mi"
  JOB_MEMORY_LIMIT: "2Gi"
  
  # Worker Configuration
  WORKER_MAX_CONCURRENT_ACTIVITIES: "10"
  WORKER_MAX_CONCURRENT_WORKFLOWS: "5"
  
  # Health Check Configuration
  HEALTH_CHECK_PORT: "8090"
  
  # Logging Configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
