apiVersion: v1
kind: Secret
metadata:
  name: olake-k8s-worker-secret
  namespace: olake
  labels:
    app.kubernetes.io/name: olake-k8s-worker
    app.kubernetes.io/instance: olake
    app.kubernetes.io/component: worker
type: Opaque
data:
  DB_PASSWORD: b2xha2U=  # "olake"
