apiVersion: v1
kind: Service
metadata:
  name: olake-k8s-worker
  namespace: olake
  labels:
    app.kubernetes.io/name: olake-k8s-worker
    app.kubernetes.io/instance: olake
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: health
    protocol: TCP
    name: health
  selector:
    app.kubernetes.io/name: olake-k8s-worker
    app.kubernetes.io/instance: olake
    app.kubernetes.io/component: worker
