# Simplified temporal deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  namespace: olake
  labels:
    app: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
      - name: temporal
        image: temporalio/auto-setup:1.22.3
        ports:
        - containerPort: 7233
        - containerPort: 7234
        - containerPort: 7235
        - containerPort: 7239
        env:
        - name: DB
          value: "postgres12"
        - name: DB_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "temporal"
        - name: POSTGRES_PWD
          value: "temporal"
        - name: POSTGRES_SEEDS
          value: "postgresql.olake.svc.cluster.local"
        - name: ENABLE_ES
          value: "true"
        - name: ES_SEEDS
          value: "elasticsearch.olake.svc.cluster.local"
        - name: ES_VERSION
          value: "v7"
        - name: TEMPORAL_ADDRESS
          value: "temporal.olake.svc.cluster.local:7233"
        - name: TEMPORAL_CLI_ADDRESS
          value: "temporal.olake.svc.cluster.local:7233"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 7233
          initialDelaySeconds: 60
          periodSeconds: 10
