apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: olake
  labels:
    app: temporal
spec:
  selector:
    app: temporal
  ports:
  - name: frontend
    port: 7233
    targetPort: 7233
  - name: history
    port: 7234
    targetPort: 7234
  - name: matching
    port: 7235
    targetPort: 7235
  - name: worker
    port: 7239
    targetPort: 7239
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP
