apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui
  namespace: olake
  labels:
    app: temporal-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-ui
  template:
    metadata:
      labels:
        app: temporal-ui
    spec:
      containers:
      - name: temporal-ui
        image: temporalio/ui:2.16.2
        ports:
        - containerPort: 8081
        env:
        - name: TEMPORAL_ADDRESS
          value: "temporal.olake.svc.cluster.local:7233"
        - name: TEMPORAL_UI_PORT
          value: "8081"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
