apiVersion: v1
kind: Service
metadata:
  name: temporal-ui
  namespace: olake
  labels:
    app: temporal-ui
spec:
  selector:
    app: temporal-ui
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort
