apiVersion: v2
name: olake
description: A Helm chart for OLake - Fastest open-source tool for replicating Databases to Apache Iceberg or Data Lakehouse
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/datazip-inc/olake-ui
sources:
  - https://github.com/datazip-inc/olake-ui
keywords:
  - data-pipeline
  - elt
  - kubernetes
  - workflow
  - olake
maintainers:
  - name: Schitiz Sharma
    email: schitiz@datazip.io
  - name: Team OLake
    email: hello@olake.io
dependencies: []
annotations:
  # Enable schema validation for this chart
  helm.sh/schema-validation: "true"