apiVersion: v1
kind: Secret
metadata:
  name: olake-workers-secret
  namespace: {{ include "olake.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "53"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "olake.labels" . | nindent 4 }}
    app.kubernetes.io/component: workers
type: Opaque
data:
  DB_PASSWORD: {{ .Values.postgresql.auth.postgresPassword | b64enc }}