{{- if .Values.olakeWorker.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: olake-k8s-worker-secret
  namespace: {{ .Values.namespace.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "53"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app.kubernetes.io/name: olake-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: worker
    {{- include "olake.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ tpl .Values.olakeWorker.config.database.password . | b64enc }}
{{- end }}