{{- if .Values.olakeWorker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: olake-k8s-worker
  namespace: {{ .Values.namespace.name }}
  {{- with (.Values.olakeWorker.service.annotations | default dict) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: olake-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: worker
    {{- include "olake.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 8090
    targetPort: 8090
    protocol: TCP
    name: health
  selector:
    app.kubernetes.io/name: olake-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: worker
{{- end }}