{{- if .Values.olakeUI.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: olake-ui
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: olake-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ui
    {{- include "olake.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: olake-ui
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: olake-ui
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: ui
    spec:
      containers:
      - name: olake-ui
        image: "{{ .Values.olakeUI.image.repository }}:{{ .Values.olakeUI.image.tag }}"
        imagePullPolicy: {{ .Values.olakeUI.image.pullPolicy }}
        ports:
        - name: backend
          containerPort: {{ .Values.olakeUI.service.ports.backend }}
          protocol: TCP
        - name: frontend
          containerPort: {{ .Values.olakeUI.service.ports.frontend }}
          protocol: TCP
        envFrom:
        - configMapRef:
            name: olake-ui-config
        resources:
          {{- toYaml .Values.olakeUI.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /health
            port: backend
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: backend
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
{{- end }}