apiVersion: batch/v1
kind: Job
metadata:
  name: olake-signup-init
  namespace: olake
  labels:
    app: olake-ui
    component: signup-init
spec:
  # Ensure job runs only once
  completions: 1
  parallelism: 1
  backoffLimit: 0  # Don't retry on failure
  template:
    spec:
      containers:
      - name: signup-init
        image: curlimages/curl:latest
        env:
        - name: USERNAME
          value: "admin"
        - name: PASSWORD
          value: "password"
        - name: EMAIL
          value: "admin@example.com"
        - name: OLAKE_APP_URL
          value: "http://olake-ui.olake.svc.cluster.local:8080/signup"
        command:
        - /bin/sh
        - -c
        - |
          echo 'signup-init: Starting signup initialization...'
          echo "signup-init: Target URL: $OLAKE_APP_URL"
          
          echo 'signup-init: Attempting to create admin user...'
          
          response=$(curl -s -w "%{http_code}" -o /tmp/response.json \
            -X POST "$OLAKE_APP_URL" \
            -H "Content-Type: application/json" \
            -d "{\"username\":\"$USERNAME\",\"password\":\"$PASSWORD\",\"email\":\"$EMAIL\"}")
          
          # The actual response body from olake-ui will be printed to stderr by the '-o /dev/stderr' curl option.
          # A newline after stderr output from curl can make logs cleaner.
          echo ''
          
          if ! [ "$response" -eq "$response" ] 2>/dev/null; then
              echo "signup-init: ERROR - HTTP_RESPONSE_CODE is not a number: '$response'"
              exit 1
          fi
          
          if [ "$response" -ge 200 ] && [ "$response" -lt 300 ]; then
            echo "signup-init: User '$USERNAME' creation request successful (HTTP $response)."
          elif [ "$response" = "409" ] || [ "$response" = "400" ]; then
            echo "signup-init: User '$USERNAME' may already exist (HTTP $response). This is okay."
          else
            echo "signup-init: User '$USERNAME' creation request FAILED (HTTP $response). Server response body above."
            exit 1
          fi
          echo 'signup-init: User setup process complete.'
      restartPolicy: Never
  # Automatically clean up completed jobs after 1 hour
  ttlSecondsAfterFinished: 3600
