apiVersion: v1
kind: Service
metadata:
  name: olake-ui
  namespace: olake
  labels:
    app: olake-ui
spec:
  selector:
    app: olake-ui
  ports:
  - name: backend
    port: 8080
    targetPort: backend
    nodePort: 30081
    protocol: TCP
  - name: frontend
    port: 8000
    targetPort: frontend
    nodePort: 30082
    protocol: TCP
  type: NodePort

