name-template: "DZ-Cloud v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "kind/feature"
      - "kind/enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "kind/fix"
      - "kind/bugfix"
      - "kind/bug"
  - title: "🧰 Maintenance"
    labels:
      - "kind/chore"
      - "area/ci"
      - "area/tests"
  - title: 📖 Documentation
    label: area/docs
  - title: 🔒 Security
    label: security
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## What's New
  ## 🔤 General
  $CHANGES

  ## 👨🏽‍💻 Contributors

  Thank you to our contributors for making this release possible:
  $CONTRIBUTORS
autolabeler:
  - label: "area/ci"
    branch:
      - "/.github/"
