apiVersion: apps/v1
kind: Deployment
metadata:
  name: olake-k8s-worker
  namespace: olake
  labels:
    app.kubernetes.io/name: olake-k8s-worker
    app.kubernetes.io/instance: olake
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: olake-k8s-worker
      app.kubernetes.io/instance: olake
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: olake-k8s-worker
        app.kubernetes.io/instance: olake
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: olake-k8s-worker
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: olake-k8s-worker
        image: olakego/olake-k8s-worker:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: health
          containerPort: 8090
          protocol: TCP
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: olake-k8s-worker-secret
              key: DB_PASSWORD
        envFrom:
        - configMapRef:
            name: olake-k8s-worker-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: health
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: health
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
