{{- if .Values.nfsServer.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "olake.fullname" . }}-nfs
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/resource-policy": "keep"
  labels:
    {{- include "olake.labels" . | nindent 4 }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
{{- end }}