{{- if .Values.nfsServer.enabled }}
{{- /* Define a static name for the StorageClass */}}
{{- $scName := .Values.nfsServer.storageClass.name | default "nfs-server" -}}

{{- /* Use 'lookup' to see if the StorageClass already exists. */}}
{{- /* The empty "" for namespace is correct for a cluster-scoped resource. */}}
{{- $existingSc := lookup "storage.k8s.io/v1" "StorageClass" "" $scName -}}

{{- /* Only render the template if the StorageClass does not exist */}}
{{- if not $existingSc }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $scName }}
  annotations:
    # This policy is still important to prevent deletion on `helm uninstall`.
    "helm.sh/resource-policy": keep
  labels:
    app.kubernetes.io/name: {{ include "olake.name" . }}-nfs-server
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: storage-class
provisioner: {{ include "olake.fullname" . }}/nfs-server
parameters: {}
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - vers=4.1
  - rsize=1048576
  - wsize=1048576
  - hard
  - timeo=600
  - retrans=2
{{- end }}
{{- end }}