{{- if .Values.nfsServer.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "olake.fullname" . }}-nfs-pv
  annotations: {}
  labels:
    {{- include "olake.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.nfsServer.persistence.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "olake.fullname" . }}-nfs
  nfs:
    server: {{ include "olake.nfsStaticIP" . }}
    path: /
{{- end }}