{{- if .Values.nfsServer.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "olake.fullname" . }}-nfs-pv
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "olake.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.nfsServer.persistence.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "olake.fullname" . }}-nfs
  nfs:
    server: "192.168.100.100"
    path: /
{{- end }}