{{- if .Values.nfsServer.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "olake.fullname" . }}-nfs-cidr-detection
  namespace: {{ .Values.namespace.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app.kubernetes.io/name: {{ include "olake.name" . }}-cidr-detection
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: nfs-cidr-detection
    {{- include "olake.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "olake.fullname" . }}-nfs-cidr-detection
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app.kubernetes.io/name: {{ include "olake.name" . }}-cidr-detection
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: nfs-cidr-detection
    {{- include "olake.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete", "get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "update", "patch", "get", "list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "olake.fullname" . }}-nfs-cidr-detection
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app.kubernetes.io/name: {{ include "olake.name" . }}-cidr-detection
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: nfs-cidr-detection
    {{- include "olake.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "olake.fullname" . }}-nfs-cidr-detection
subjects:
- kind: ServiceAccount
  name: {{ include "olake.fullname" . }}-nfs-cidr-detection
  namespace: {{ .Values.namespace.name }}
{{- end }}