apiVersion: apps/v1
kind: Deployment
metadata:
  name: olake-ui
  namespace: olake
  labels:
    app: olake-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olake-ui
  template:
    metadata:
      labels:
        app: olake-ui
    spec:
      containers:
      - name: olake-ui
        image: olakego/olake-ui:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_BASE_URL
          value: "http://olake-server.olake.svc.cluster.local:8080"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
