apiVersion: apps/v1
kind: Deployment
metadata:
  name: olake-server
  namespace: olake
  labels:
    app: olake-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olake-server
  template:
    metadata:
      labels:
        app: olake-server
    spec:
      containers:
      - name: olake-server
        image: olakego/olake-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: APP_CONF
          value: "/app/conf/app.conf"
        volumeMounts:
        - name: server-config
          mountPath: /app/conf
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: server-config
        configMap:
          name: olake-server-config
