apiVersion: v1
kind: ConfigMap
metadata:
  name: olake-k8s-worker-config
  namespace: olake
  labels:
    app.kubernetes.io/name: olake-k8s-worker
    app.kubernetes.io/instance: olake
    app.kubernetes.io/component: worker
data:
  # Temporal configuration
  TEMPORAL_ADDRESS: "temporal.olake.svc.cluster.local:7233"
  
  # Database configuration
  DB_HOST: "postgres.olake.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "olake"
  DB_USER: "olake"
  DB_SSLMODE: "disable"
  RUN_MODE: "development"
  DB_MAX_OPEN_CONNS: "25"
  DB_MAX_IDLE_CONNS: "5"
  DB_CONN_MAX_LIFETIME: "5m"
  
  # Kubernetes configuration
  WORKER_NAMESPACE: "olake"
  IMAGE_REGISTRY: "olakego"
  IMAGE_PULL_POLICY: "IfNotPresent"
  SERVICE_ACCOUNT: "olake-k8s-worker"
  JOB_TTL_SECONDS: "86400"  # 24 hours
  CLEANUP_POLICY: "auto"
  
  # Resource defaults
  DEFAULT_CPU_REQUEST: "100m"
  DEFAULT_CPU_LIMIT: "500m"
  DEFAULT_MEMORY_REQUEST: "256Mi"
  DEFAULT_MEMORY_LIMIT: "1Gi"
  
  # Worker configuration
  MAX_CONCURRENT_ACTIVITIES: "10"
  MAX_CONCURRENT_WORKFLOWS: "5"
  HEARTBEAT_INTERVAL: "5s"
  
  # Logging configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "console"
  LOG_STRUCTURED: "false"
