apiVersion: v1
kind: ServiceAccount
metadata:
  name: olake-k8s-worker
  namespace: olake
  labels:
    app.kubernetes.io/name: olake-k8s-worker
    app.kubernetes.io/instance: olake
    app.kubernetes.io/component: worker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: olake-k8s-worker
  namespace: olake
  labels:
    app.kubernetes.io/name: olake-k8s-worker
    app.kubernetes.io/instance: olake
    app.kubernetes.io/component: worker
rules:
# Job management permissions
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs/status"]
  verbs: ["get", "list", "watch"]
# ConfigMap management permissions
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# Pod management permissions (for getting logs)
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
# Events permissions (for debugging)
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: olake-k8s-worker
  namespace: olake
  labels:
    app.kubernetes.io/name: olake-k8s-worker
    app.kubernetes.io/instance: olake
    app.kubernetes.io/component: worker
subjects:
- kind: ServiceAccount
  name: olake-k8s-worker
  namespace: olake
roleRef:
  kind: Role
  name: olake-k8s-worker
  apiGroup: rbac.authorization.k8s.io
