apiVersion: apps/v1
kind: Deployment
metadata:
  name: olake-ui
  namespace: olake
  labels:
    app: olake-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olake-ui
  template:
    metadata:
      labels:
        app: olake-ui
    spec:
      containers:
      - name: olake-ui
        image: olake-ui:local
        imagePullPolicy: Never
        ports:
        - name: backend
          containerPort: 8080
          protocol: TCP
        - name: frontend
          containerPort: 8000
          protocol: TCP
        env:
        - name: PERSISTENT_DIR
          value: "/tmp/olake-config"
        - name: POSTGRES_DB
          value: "postgres://temporal:temporal@postgresql.olake.svc.cluster.local:5432/postgres"
        volumeMounts:
        - name: olake-config
          mountPath: /opt/backend/conf
        - name: shared-storage
          mountPath: /tmp/olake-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: backend
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: backend
          initialDelaySeconds: 30
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
          capabilities:
            drop:
            - ALL
      volumes:
      - name: olake-config
        configMap:
          name: olake-config
      - name: shared-storage
        persistentVolumeClaim:
          claimName: olake-jobs-pvc