{{- if .Values.temporal.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: workflow-engine
    {{- include "olake.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: temporal
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: workflow-engine
  template:
    metadata:
      labels:
        app.kubernetes.io/name: temporal
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: workflow-engine
    spec:
      containers:
      - name: temporal
        image: "{{ .Values.temporal.server.image.repository }}:{{ .Values.temporal.server.image.tag }}"
        imagePullPolicy: {{ .Values.temporal.server.image.pullPolicy }}
        ports:
        - name: grpc
          containerPort: {{ .Values.temporal.server.service.port }}
          protocol: TCP
        env:
        {{- range .Values.temporal.server.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.temporal.server.resources | nindent 10 }}
        readinessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        livenessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
{{- end }}