{{- if .Values.temporal.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  namespace: {{ .Values.namespace.name }}
  annotations: {}
  labels:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: workflow-engine
    {{- include "olake.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.temporal.server.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: temporal
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: workflow-engine
  template:
    metadata:
      annotations:
        {{- with .Values.temporal.server.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/name: temporal
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: workflow-engine
        {{- with .Values.temporal.server.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.temporal.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.temporal.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.temporal.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.global.securityContext | nindent 8 }}
      initContainers:
      - name: wait-for-postgresql
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for PostgreSQL to be ready..."
          until nc -z postgresql.{{ .Values.namespace.name }}.svc.cluster.local 5432; do
            echo "PostgreSQL is not ready yet. Waiting..."
            sleep 5
          done
          echo "PostgreSQL is ready!"
      containers:
      - name: temporal
        image: "{{ .Values.temporal.server.image.repository }}:{{ .Values.temporal.server.image.tag }}"
        imagePullPolicy: {{ .Values.temporal.server.image.pullPolicy }}
        ports:
        - name: grpc
          containerPort: 7233
          protocol: TCP
        env:
        {{- range .Values.temporal.server.env }}
        - name: {{ .name }}
          value: {{ tpl .value $ | quote }}
        {{- end }}
        {{- $defaultResources := dict 
          "requests" (dict "memory" "512Mi" "cpu" "500m")
        }}
        {{- $resources := mergeOverwrite $defaultResources (.Values.temporal.server.resources | default dict) }}
        resources:
          {{- toYaml $resources | nindent 10 }}
        {{- $defaultReadinessProbe := dict 
          "initialDelaySeconds" 10
          "periodSeconds" 10
          "timeoutSeconds" 5
          "failureThreshold" 3
          "successThreshold" 1
          "tcpSocket" (dict "port" 7233)
        }}
        {{- $readinessProbe := mergeOverwrite $defaultReadinessProbe (.Values.temporal.server.readinessProbe | default dict) }}
        readinessProbe:
          {{- toYaml $readinessProbe | nindent 10 }}
        {{- $defaultLivenessProbe := dict 
          "initialDelaySeconds" 150
          "periodSeconds" 60
          "timeoutSeconds" 10
          "failureThreshold" 3
          "successThreshold" 1
          "tcpSocket" (dict "port" 7233)
        }}
        {{- $livenessProbe := mergeOverwrite $defaultLivenessProbe (.Values.temporal.server.livenessProbe | default dict) }}
        livenessProbe:
          {{- toYaml $livenessProbe | nindent 10 }}
{{- end }}