{{- if .Values.temporal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: workflow-engine
    {{- include "olake.labels" . | nindent 4 }}
spec:
  type: {{ .Values.temporal.server.service.type }}
  ports:
  - port: {{ .Values.temporal.server.service.port }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  selector:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: workflow-engine
{{- end }}