{{- if .Values.elasticsearch.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace.name }}
  annotations: {}
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: search
    {{- include "olake.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.elasticsearch.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: elasticsearch
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: search
  template:
    metadata:
      annotations:
        {{- with .Values.elasticsearch.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/name: elasticsearch
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: search
        {{- with .Values.elasticsearch.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.elasticsearch.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.elasticsearch.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.elasticsearch.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.global.securityContext | nindent 8 }}
      containers:
      - name: elasticsearch
        image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
        imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.elasticsearch.service.port }}
          protocol: TCP
        - name: transport
          containerPort: 9300
          protocol: TCP
        env:
        {{- range .Values.elasticsearch.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.elasticsearch.resources | nindent 10 }}
        {{- if .Values.elasticsearch.readinessProbe.enabled }}
        readinessProbe:
          initialDelaySeconds: {{ .Values.elasticsearch.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.elasticsearch.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.elasticsearch.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.elasticsearch.readinessProbe.failureThreshold }}
          successThreshold: {{ .Values.elasticsearch.readinessProbe.successThreshold }}
          {{- with .Values.elasticsearch.readinessProbe.httpGet }}
          httpGet:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if .Values.elasticsearch.livenessProbe.enabled }}
        livenessProbe:
          initialDelaySeconds: {{ .Values.elasticsearch.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.elasticsearch.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.elasticsearch.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.elasticsearch.livenessProbe.failureThreshold }}
          successThreshold: {{ .Values.elasticsearch.livenessProbe.successThreshold }}
          {{- with .Values.elasticsearch.livenessProbe.httpGet }}
          httpGet:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
{{- end }}