apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  namespace: olake
  labels:
    app: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      initContainers:
      - name: temporal-sql-tool
        image: temporalio/admin-tools:1.22.0
        command: ["/bin/bash", "-c"]
        args:
        - |
          set -e
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h postgresql.olake.svc.cluster.local -p 5432 -U postgres; do
            echo "PostgreSQL is not ready yet..."
            sleep 2
          done
          echo "PostgreSQL is ready!"
          
          echo "Setting up Temporal database schema..."
          temporal-sql-tool --plugin postgres --ep postgresql.olake.svc.cluster.local:5432 --u temporal --pw temporal --db temporal setup-schema -v 0.0
          temporal-sql-tool --plugin postgres --ep postgresql.olake.svc.cluster.local:5432 --u temporal --pw temporal --db temporal update-schema -d /etc/temporal/schema/postgresql/v96
          
          echo "Setting up Temporal visibility schema..."
          temporal-sql-tool --plugin postgres --ep postgresql.olake.svc.cluster.local:5432 --u temporal --pw temporal --db temporal --visibility setup-schema -v 0.0
          temporal-sql-tool --plugin postgres --ep postgresql.olake.svc.cluster.local:5432 --u temporal --pw temporal --db temporal --visibility update-schema -d /etc/temporal/schema/postgresql/visibility/versioned
        env:
        - name: PGPASSWORD
          value: "temporal"
      containers:
      - name: temporal
        image: temporalio/auto-setup:1.22.0
        ports:
        - containerPort: 7233
        - containerPort: 7234
        - containerPort: 7235
        - containerPort: 7239
        - containerPort: 9090
        env:
        - name: DB
          value: "postgresql"
        - name: DB_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "temporal"
        - name: POSTGRES_PWD
          value: "temporal"
        - name: POSTGRES_SEEDS
          value: "postgresql.olake.svc.cluster.local"
        - name: DYNAMIC_CONFIG_FILE_PATH
          value: "config/dynamicconfig/development-sql.yaml"
        volumeMounts:
        - name: temporal-config
          mountPath: /etc/temporal/config/config_template.yaml
          subPath: config_template.yaml
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 7233
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 7233
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: temporal-config
        configMap:
          name: temporal-config
