apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui
  namespace: olake
  labels:
    app: temporal-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-ui
  template:
    metadata:
      labels:
        app: temporal-ui
    spec:
      containers:
      - name: temporal-ui
        image: temporalio/ui:2.21.3
        ports:
        - containerPort: 8080
        env:
        - name: TEMPORAL_ADDRESS
          value: "temporal.olake.svc.cluster.local:7233"
        - name: TEMPORAL_CORS_ORIGINS
          value: "http://localhost:3000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
