apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: olake
  labels:
    app: elasticsearch
spec:
  type: ClusterIP
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
    name: http
  selector:
    app: elasticsearch
