export enum AnalyticsEvent {
	TestConnectionSource = "test_connection_source",
	TestConnectionDestination = "test_connection_destination",
	CreateJobClicked = "create_job_clicked",
	CreateSourceClicked = "create_source_clicked",
	CreateDestinationClicked = "create_destination_clicked",
	AddCatalogClicked = "add_catalog_clicked",
	ImportCatalogFromDestinationClicked = "import_catalog_from_destination_clicked",
	CatalogConnectClicked = "catalog_connect_clicked",
	ViewTableMetricsClicked = "view_table_metrics_clicked",
	ConfigureButtonClicked = "configure_button_clicked",
	BulkConfigureClicked = "bulk_configure_clicked",
	FrequencySelected = "frequency_selected",
	FrequencyOptionClicked = "frequency_option_clicked",
	ConfigurationSaveClicked = "configuration_save_clicked",
	ConfigurationSaveSuccessful = "configuration_save_successful",
	ConfigurationSaveFailed = "configuration_save_failed",
	StatusToggleOnClicked = "status_toggle_on_clicked",
	StatusToggleOffClicked = "status_toggle_off_clicked",
	StatusEnableSuccessful = "status_enable_successful",
	StatusEnableFailed = "status_enable_failed",
	StatusRetryClicked = "status_retry_clicked",
	ViewLogsClicked = "view_logs_clicked",
	HealthScoreTooltipViewed = "health_score_tooltip_viewed",
	TargetFileSizeCustomized = "target_file_size_customized",
	MaintenanceModuleOpened = "maintenance_module_opened",
}
