name: Integration Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  integration-tests:
    runs-on: 16gb-runner
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'
      
      - name: Download Go dependencies
        working-directory: ./server
        run: go mod download

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Start Test Infrastructure
        run: |
            docker compose -f ./server/tests/docker-compose.yml up -d
            curl -fsSL -o docker-compose.destination.yml \
                https://raw.githubusercontent.com/datazip-inc/olake/master/destination/iceberg/local-test/docker-compose.yml
            docker compose -f docker-compose.destination.yml up -d minio mc postgres spark-iceberg

      - name: Wait for PostgreSQL
        uses: nick-fields/retry@v2
        with:
            timeout_minutes: 5
            max_attempts: 30
            retry_wait_seconds: 5
            command: |
                docker exec olake_postgres-test psql -h localhost -U postgres -d postgres -c "SELECT 1"

      - name: Install Playwright dependencies
        working-directory: ./ui
        run: |
            pnpm add -D @playwright/test
            pnpm exec playwright install --with-deps chromium

      - name: Run Docker In Docker Container Test
        working-directory: ./server
        run: go test -v ./tests -timeout 0 -run 'TestDinDIntegration'

      - name: Cleanup
        if: always()
        run: |
          docker compose -f ./server/tests/docker-compose.yml down
          docker compose -p olake -f docker-compose.destination.yml down
